////////////////////////////////////////////////////////////////////////
//
// DataValueValidator.java
//
// This file was generated by MapForce 2017sp2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.text.edi;

public class DataValueValidator {

	public boolean isIncomplete() {
		return false;
	}

	public boolean hasValue(String value) {
		return true;
	}

	public String getCodeListValues() {
		return "";
	}

}
