/**
 * SourceInstanceUnavailableException.java
 *
 * This file was generated by MapForce 2017sp2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.altova;


public class SourceInstanceUnavailableException extends RuntimeException {

	public SourceInstanceUnavailableException(String text)
	{
		super(text);
	}

	public SourceInstanceUnavailableException(String text, Throwable other)
	{
		super(text, other);
	}

}
