/**
 * UserException.java
 *
 * This file was generated by MapForce 2017sp2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.altova;


public class UserException extends RuntimeException 
{
	protected String	message;
	protected org.w3c.dom.Node node;

	public UserException(String text) 
	{
		message = text;
		node = null;
	}

	public UserException(org.w3c.dom.Node n) 
	{
		message = null;
		node = n;
	}

	public UserException(String text, org.w3c.dom.Node n) 
	{
		message = text;
		node = n;
	}

	public String getMessage() {
		return message;
	}

	public org.w3c.dom.Node getNode() {
		return node;
	}
}
